# This should be environment specific

#Hibernate
hibernate:
  connection:
    autocommit: false
  format_sql: true
  hbm2ddl:
    auto: validate
  show_sql: false
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  dialect: org.hibernate.dialect.PostgreSQLDialect

#Database
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/circletest
  username: root
  password:
