# This configuration should be fetched from Spring Cloud Config
# environment specific configuration

#Database
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 900811

feign:
  client:
    config:
      test:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
