# This configuration should be fetched from Spring Cloud Config
# Common configuration across different environments

#Spring Service Registry
eureka:
  client:
    enabled: false

spring:
  http:
    converters:
      preferred-json-mapper: gson
