version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk-node
        environment:
          SPRING_PROFILES_ACTIVE: ci
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circletest

    steps:
      - checkout
      - restore_cache:
          key: v1-template-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn -Dflyway.configFile=configuration/db/${SPRING_PROFILES_ACTIVE}.properties flyway:clean flyway:migrate
      - run: mvn clean -Dskip.surefire.tests=false -D=skip.failsafe.tests=false verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - run: mvn clean package
      - store_artifacts:
          path: target/deliverable.jar
      - store_artifacts:
          path: target/site
      - save_cache:
          key: v1-template-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

